version: "3.9"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ss8
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # test: ["CMD", "pg_isready", "-U", "admin", "-d", "books"]
      test: ["CMD-SHELL", "pg_isready -U $DATABASE_USERNAME -d $DATABASE_NAME"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    env_file:
      - .env

  django-web:
    build: .
    container_name: django-docker
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DJANGO_SETTINGS_MODULE: myproject.settings
    volumes:
      - ./books:/app/books  # Ensure the path is correct for the project directory
      - ./media:/app/media  # Mounts 'media' to '/app/media' inside the container
      - ./books/static:/app/books/staticfiles  # Ensure static files are accessible
    env_file:
      - .env
    command: ["sh", "-c", "python /app/manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application"]

volumes:
  postgres_data:
