# Generated by Django 5.1.5 on 2025-01-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='book_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='book_price',
        ),
    ]
